spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: consulta
          uri: lb://CONSULTA-SERVICE
          predicates:
            - Path=/consulta/**
          filters:
            - StripPrefix=1

        - id: medico
          uri: lb://MEDICO-SERVICE
          predicates:
            - Path=/medico/**
          filters:
            - StripPrefix=1

        - id: paciente
          uri: lb://PACIENTE-SERVICE
          predicates:
            - Path=/paciente/**
          filters:
            - StripPrefix=1

        - id: notafiscal
          uri: lb://NOTA-FISCAL-SERVICE
          predicates:
            - Path=/notafiscal/**
          filters:
            - StripPrefix=1
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka