spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: consulta
          uri: lb://CONSULTA-SERVICE
          predicates:
            - Path=/consulta/**
          filters:
            - StripPrefix=1
server:
  port: 9999
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka