spring:
  application:
    name: nota-fiscal-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:notafiscal
    username: sa
    password: 123456
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

  rabbitmq:
    host: RABBITMQ
    port: 5672
    username: clinica
    password: 123456

server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://EUREKA-SERVER:8761/eureka
