INSERT INTO PACIENTE(nome) VALUES ('GLADSON ALBUQUERQUE');
INSERT INTO PACIENTE(nome) VALUES ('LEONARDO GLORIA');
INSERT INTO PACIENTE(nome) VALUES ('BELTRANO DA SILVA');
INSERT INTO PACIENTE(nome) VALUES ('CICRANO DA PAZ');