spring:
  profiles:
    active: docker
  application:
    name: consulta-service
  config:
    import: optional:configserver:http://localhost:8888
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:consulta
    username: ${db.user}
    password: ${db.password}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
app:
  myport: ${PORT:0}
server:
  port: ${app.myport}
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
