spring:
  application:
    name: consulta-service
  config:
    import: optional:configserver:http://config-server:8888
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:consulta
    username: ${db.user}
    password: ${db.password}
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://EUREKA-SERVER:8761/eureka
