INSERT INTO MEDICO(nome) VALUES ('JOÃO PARENTESCO');
INSERT INTO MEDICO(nome) VALUES ('ADELMAR DO BRONKS');
INSERT INTO MEDICO(nome) VALUES ('VILLAS BOAS RAPAZ');
INSERT INTO MEDICO(nome) VALUES ('MOLUCO BELEZA');